# Generated by Django 4.2.27 on 2026-02-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nms_method', models.CharField(choices=[('standard', 'Standard NMS'), ('soft', 'Soft-NMS'), ('diou', 'DIoU-NMS')], default='standard', max_length=10)),
                ('confidence_threshold', models.FloatField(default=0.25)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('soft_nms_sigma', models.FloatField(default=0.5)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('result_video', models.FileField(blank=True, null=True, upload_to='results/')),
                ('processing_time', models.FloatField(default=0.0)),
                ('fps', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detection Session',
                'verbose_name_plural': 'Detection Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Uploaded Media',
                'verbose_name_plural': 'Uploaded Media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_objects', models.PositiveIntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('class_distribution', models.JSONField(default=dict)),
                ('occluded_objects', models.PositiveIntegerField(default=0)),
                ('avg_occlusion_score', models.FloatField(default=0.0)),
                ('inference_time', models.FloatField(default=0.0)),
                ('nms_time', models.FloatField(default=0.0)),
                ('total_frames', models.PositiveIntegerField(default=1)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mAP', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='detection.detectionsession')),
            ],
            options={
                'verbose_name': 'Performance Metrics',
                'verbose_name_plural': 'Performance Metrics',
            },
        ),
        migrations.CreateModel(
            name='NMSComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.25)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('soft_nms_sigma', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diou_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diou_comparisons', to='detection.detectionsession')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='detection.uploadedmedia')),
                ('soft_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_comparisons', to='detection.detectionsession')),
                ('standard_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_comparisons', to='detection.detectionsession')),
            ],
            options={
                'verbose_name': 'NMS Comparison',
                'verbose_name_plural': 'NMS Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='detectionsession',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='detection.uploadedmedia'),
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField(default=0)),
                ('class_id', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('is_occluded', models.BooleanField(default=False)),
                ('occlusion_score', models.FloatField(default=0.0)),
                ('overlapping_objects', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detection.detectionsession')),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-confidence'],
            },
        ),
    ]
