# Generated by Django 4.2.27 on 2026-02-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsession',
            name='driving_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionsession',
            name='environment_warning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
